Feature/ledger manual registration 334
MONEYMONG/iOS-Moneymong pull request #14
Opened 2024-04-20 11:18 UTC by Siwon-L

## 작업 내용

- [ ] 장부, 멤버 tab 추가
- [ ] flotingButton 추가
- [ ] 하위 view coordinator 및 dicontainer 구현

## 리뷰어에게 (필요시)
coordinator, dicontainer 구현했는데 좀 봐주시면 좋을 것 같습니다.
장부 tab에 flotingButton만 추가한 상태이고, 이후 수동 등록 구현 할 생각입니다.

## 스크린샷 (필요시)
<img src="https://github.com/MONEYMONG/iOS-Moneymong/assets/91936941/6d6cf72a-fe6e-425c-a62c-9e678fff8292" width="200">

2024-04-21 10:38 UTC, FirstDo requested changes
Coordinator, DIContainer를 따로 만들 필요가 있을까요?

제 생각엔 한 flow가 한 Coordinator를 나타내는거고
장부던 맴버던 같은 flow상에 있는데, 두개를 굳이 나눠놀 필요가 없어보입니다

모드 LedgerCoordinator, LedgerContainer내에서 해결하는게 맞아보이는데 어떻게 생각하세요?

2024-04-21 13:25 UTC, Siwon-L commented
Coordinator, DIContainer 제거 해서 커밋 했습니다.
근데 한가지 고민이 있는게
ledgerTabVC의 table view item을 클릭했을 때 ledgerVC에서 상세페이지로 push가 되어야 하는데
저는 해당 처리를 coordinator끼리 하려했는데 coordinator가 없으니 어떻게 처리 해야할지 고민이 되네요.

2024-04-21 23:29 UTC, FirstDo approved these changes

2024-04-21 23:29 UTC, FirstDo commented on Projects/Feature/Ledger/Sources/Ledger/TabItems/Member/MemberTabReactor.swift
> +final class MemberTabReactor: Reactor {
이거 저번에도 물어본건데
MemberTabReactor -> LedgerReactor로의 이벤트 전달은 어떻게 하나요?? 
noti말고, 전역스테이트 말고는 진짜 방법이 없는거임? ㅠㅠ

+ LedgerReactor를 공유하는건 어떻게 생각??

2024-04-21 23:29 UTC, FirstDo commented on Projects/Feature/Ledger/Sources/LedgerDIContainer.swift
> +    vc.title = "장부"
[P1] 요거 이렇게 하면 안됩니다. 물론 일단 그냥 해놓으신 거겠지만
네이게이션 title 세팅하는 매서드를 만들어놨어요
DesignSystem Extension의 `setTitle(:)` 매서드 참고

2024-04-22 03:01 UTC, Siwon-L commented on Projects/Feature/Ledger/Sources/Ledger/TabItems/Member/MemberTabReactor.swift
> +final class MemberTabReactor: Reactor {
사실 저도 그게 고민인데 
MemberTabReactor -> LedgerReactor로의 이벤트 전달은 다 화면 전환에 관련된 이벤트이기 때문에 전 coordinator를 통해 이벤트를 전달하려고 했어요.
Coordinator를 공유하거나, 두두 말대로 Reactor를 공유하는 방법으로 진행하긴 해야할것 같아요.

2024-04-22 03:03 UTC, Siwon-L commented on Projects/Feature/Ledger/Sources/LedgerDIContainer.swift
> +    vc.title = "장부"
저거 네비게이션 타이틀 설정한거 아닙니다. 
tap title이에요.

2024-04-22 12:03 UTC, malrang-malrang approved these changes
고생하셨어용 사파리 ~~ :)

2024-04-22 12:03 UTC, malrang-malrang commented on Projects/Feature/Ledger/Sources/Ledger/TabItems/Member/MemberTabReactor.swift
> +final class MemberTabReactor: Reactor {
이부분 어제 사파리 있을때 같이 얘기했던 부분이었는데 두두 의견 궁금해서 남깁니다!(다들 이런 상황에 어떻게 처리하나 궁금해서용)

저 같은 경우 MemberTabVC 에서 Action 받으면 LedgerVC 랑 바인딩해서 이벤트 전달 하게끔 할거같은데용!
혹은 Coordinator 를 하위(MemberTabVC) 한테 주입 해준다거나...

두두는 이런상황에서 Reactor 공유하는 방향이신가용??

2024-04-22 13:29 UTC, Siwon-L commented on Projects/Feature/Ledger/Sources/Ledger/LedgerVC.swift
> +  weak var coordinator: Coordinator?
이 부분은 당장 LedgerCoordinator일 필요가 없어서 일단 Coordinator로 정의했습니다.
차후 고민해볼 생각입니다.

2024-04-22 13:31 UTC, merged