D-5 장부 상세내역 수정 구현 - 332
MONEYMONG/iOS-Moneymong pull request #40
Opened 2024-05-28 16:47 UTC by malrang-malrang

## 작업 내용

구현한거
- [x] 장부 상세 내역 Text 변경시 수정 기능 구현(변경된 값이 있을때만 수정 API 호출)
- [x] 이미지 추가 기능 구현

구현못한거 혹은 버그
- [ ] 신규 이미지 혹은 기존 이미지 제거 (서버 이슈 있는듯합니다! 서버쪽에 문의는 남겼는데 답변을 못받았어용, 기능 자체는 구현해둠)
- [ ] 첫 진입시 read 모드 인데 Image cell deleteButton 노출되는 버그 해결
- [ ] update 모드 일때 이미지 제거할 경우 이미지추가 버튼 제거되는버그(요거 수정한거 회사에서 작업해서 못옮겨옴 29일 수정 가능)
- [ ] 첫진입시 영수증, 장부 이미지 노출되지 않는 버그(cell 높이는 적용되는데 이미지만 노출 안됨 킹피셔? 혹은 flexLayout 문제일것 같아요..)

## 리뷰어에게 (필요시)

작업이 너무 늦어지는것 같아 해결은다 못했는데 PR 합니다 ㅠ
공유하면서 수정해나갈게요!
PS- 분리 포기하고 그냥 다 VC, Reactor 하나로 커버 하게끔 바꿀까 생각도 했는데 그러면.. VC랑 Reactor 크기가 엄청.. 커질거 같아서 일단은 하던대로 진행중..

## 기본적인 설명

부모뷰 (DetailVC), 자식뷰(DetailContentsView) 로 구분지어져 있습니다.
부모뷰와 자식뷰는 LedgerDetailContentsService 를 사용해 액션과 이벤트를 주고 받습니다.

부모뷰의 역할(DetailVC)
1. 네비게이션바 관련, 
2. 하단 Confirm 버튼관련,
3. 유저 권한에 따른 수정 혹은 삭제 기능 사용 여부

자식뷰 역할(DetailContentsView)
1. read 모드 update 모드 두가지로 구성
1. 내부 컨텐츠 관련 모든것

2024-05-29 01:24 UTC, FirstDo requested changes
:) 화이팅

2024-05-29 01:24 UTC, FirstDo commented on Projects/Core/Network/Sources/Common/TargetType.swift
> +        let dd = try! JSONEncoder().encode(params)
P1 - 이부분은 수정좀 해야될듯

2024-05-29 01:24 UTC, FirstDo commented on Projects/Core/Utility/Sources/Extensions/UIView+.swift
> +}
P5 - 굳이 있어야하나 싶네요 그냥 사용하는곳에서 쓰는게 낫지않을까요?

2024-05-29 01:24 UTC, FirstDo commented on Projects/Feature/Base/Sources/Common/BaseV.swift
> +open class BaseV: UIView {
P1 - BaseV?

2024-05-29 01:24 UTC, FirstDo commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/NotificationName/NSNotification+.swift
> +  static let didTapLedgerDetailImageDeleteButton = NSNotification.Name("didTapLedgerDetailImageDeleteButton")
P5 - noti로 할필요가 있나요 안하는게 나을듯

2024-05-29 01:24 UTC, FirstDo commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +      .disposed(by: disposeBag)
P5 - 둘다 Noti 없이도 가능할거같네요

2024-05-29 01:24 UTC, FirstDo commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +  }
이게 안된다는거지?

2024-05-29 01:46 UTC, malrang-malrang commented on Projects/Core/Network/Sources/Common/TargetType.swift
> +        let dd = try! JSONEncoder().encode(params)
앗 지송 테스트 하다가 제거 안했슴당

2024-05-29 01:47 UTC, malrang-malrang commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +  }
넵넵

2024-05-29 03:09 UTC, malrang-malrang commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +      .disposed(by: disposeBag)
음/.. 요거 노티 없이 하는거 고민해보긴 했는데용

1. deleteButton Hidden
-  컬렉션뷰에 현재 스테이트 주입해서 상태 변경되면 deleteButton 히든 시키거나
-  상태 변경되면 셀자체를 delete버튼 포함된걸로 갈아끼우거나(이건 상태값 변경될때마다 셀갯수만 큼 반복문 돌려야함)

2. didTapdeleteButton
- 요거 하려면 리액터한테 딜리트 버튼 눌렀다고 바인딩 해둬야하는데 리액터 주입 해서 바인딩해서 액션 전달하도록 하는게 나았을까용

쓰다보니 그냥 콘텐츠뷰 리액터 주입해서 상태값, 액션 모두 바인딩하는게 나을수 있겠네용 :)

2024-05-29 03:13 UTC, malrang-malrang commented on Projects/Feature/Base/Sources/Common/BaseV.swift
> +open class BaseV: UIView {
UIViewController = View, UIView = View 
라는 관점으로 보면 UIView도 reactor 들고 있을수 있으니까 
또쓸일 있을까 싶어서 만들어뒀는데 불편일까용

2024-05-29 03:15 UTC, malrang-malrang commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +      .disposed(by: disposeBag)
근데 reactor 주입으로 가게되면 
contentsView -> collectionView -> Cell 한테 주입주입주입 해줘야하는 상황인데(별도의 리액터 만들어서 소통할거 아닐경우) 흠..

2024-05-30 00:39 UTC, FirstDo commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +      .disposed(by: disposeBag)
어차피 state(read, edit, delete)가 바뀌면 뷰를 다시그릴텐데
cell을 반복문 돌린다는게 무슨말인지 모르겠네여!

cell.configure(state: State, deleteAction: () -> Void)
이런식으로 만들면 되는거아님??

2024-05-30 00:58 UTC, FirstDo approved these changes

2024-05-30 06:24 UTC, Siwon-L commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +
p3 - 이미 존재하는 view를 또 만드신 이유가 있나요??? 제가 만들어 둔거와 다른 화면 같지 않아서요. 같다면 만들어져있는걸 좀 수정해서 사용하는 편이 좋을 것 같습니다.

2024-05-30 06:37 UTC, Siwon-L commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Model/LedgerDetailItem.swift
> +
이 Model은 몬가 엄청 사이즈가 큰것 같은데?? reactor가 아닌 Model에서 로직을 처리한 이유가 있을까요??

2024-05-30 11:43 UTC, malrang-malrang commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Cell/DefaultImageCell.swift
> +
맞습니다 사파리가 만드신 셀과 동일합니다! 
다만 사파리가 만드신 cell 의 위치가 제가 구현한 Detail 과 동일한 래벨의 Inputs 내부에 위치해있기 때문에 사파리가 만들어두신 셀을 재사용 하게되면 추후 유지보수 하게될경우 Detail쪽 디렉토리만 보고서는 파일을찾을수 없을거라 생각했습니다!
그래서 요거는 사파리와 협의후 Detail과 Inputs 상위로 위치하게끔 변경하여 재사용하거나 각자 두는 방향으로 진행해야겠다고 생각햇엉요!

요거 사파리 추가 답변 부탁드립니다!

2024-05-30 12:00 UTC, malrang-malrang commented on Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/Model/LedgerDetailItem.swift
> +
아 요거 고민 했던 부분이에요 ㅠ 
처음 PR 했을때는 해당 로직 들이 다 Reator 에 위치 하고 있는걸 확인 하실수 있습니다!

저도 화면에 보여져야하는 아이템 가공은 Reactor 에서 사용하는게 맞다 생각합니다!
저당시 reactor의 역할은 맞으나 저런 로직들을 Reactor에 위치하게 되면 화면 변경사항에 필요한 저장값이 아닌 API 호출용도로 사용될 프로퍼티들이 추가되어야해서 그런 프로퍼티나 상태변경을 위한 함수들이 reactor에 위치하게 되니 action이 들어오고 상태가 바뀌고 하는것들이 한눈에 잘 들어오지 않는것 같아 따로 해당역할을 해줄 객체를 만들어 사용할까 했다가 모델이 알아서 내부적으로 상태값 변경하게끔 변경했는데요!

사파리 얘기 듣고 보니 처음 처럼 reactor 에 해당로직들을 위치하고 잘 분리해서 정리시키는게 좋을듯 합니다! :)

2024-05-30 14:42 UTC, merged